# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DaDaPush.Client.Model.Action do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"type",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"type" => String.t,
    :"url" => String.t
  }
end

defimpl Poison.Decoder, for: DaDaPush.Client.Model.Action do
  def decode(value, _options) do
    value
  end
end

