# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DaDaPush.Client.Model.MessagePushRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"actions",
    :"content",
    :"needPush",
    :"title"
  ]

  @type t :: %__MODULE__{
    :"actions" => [Action] | nil,
    :"content" => String.t,
    :"needPush" => boolean(),
    :"title" => String.t
  }
end

defimpl Poison.Decoder, for: DaDaPush.Client.Model.MessagePushRequest do
  import DaDaPush.Client.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"actions", :list, DaDaPush.Client.Model.Action, options)
  end
end

