# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DaDaPush.Client.Model.MessagePushResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"messageId"
  ]

  @type t :: %__MODULE__{
    :"messageId" => integer()
  }
end

defimpl Poison.Decoder, for: DaDaPush.Client.Model.MessagePushResponse do
  def decode(value, _options) do
    value
  end
end

